### ISSUE TITLE
ImportError: cannot import name 'helperMethods' from 'ergpy' (unknown location)

### ISSUE THREAD

**Issue by Eeysirhc** [ladopixel/tERGminal#2]
Receive the following error message after I run **python ergpyMenu.py**:

`pi@raspberrypi:~/tERGminal $ python ergpyMenu.py 
Traceback (most recent call last):
  File "/home/pi/tERGminal/ergpyMenu.py", line 3, in <module>
    from ergpy import helperMethods, appkit
ImportError: cannot import name 'helperMethods' from 'ergpy' (unknown location)`

**Comment by ladopixel** [comment]
Yesterday they updated ergpy, the repository is already updated but you only have to modify:

from ergpy import helperMethods, appkit
↓
from ergpy import helper_functions, appkit

ergo = appkit.ErgoAppKit(nodeURL = 'http://159.65.11.55:9053/') 
↓
node_url: str = "http://159.65.11.55:9053/"
ergo = appkit.ErgoAppKit(node_url=node_url)

**Comment by Eeysirhc** [comment]
Fetched the updates and working as intended now. Thank you!
